---
database:
  hosts:
    database1003:
      ansible_host: 10.210.4.3

monitor:
  hosts:
    monitor1002:
      ansible_host: 10.210.2.2

cache:
  hosts:
    cache1001:
      ansible_host: 10.210.5.1

admin:
  hosts:
    admin1001:
      ansible_host: 10.210.6.1

unbound:
  hosts:
    unbound1001:
      ansible_host: 10.210.9.1

minecraft:
  hosts:
    minecraft1005:
      ansible_host: 10.210.30.5
    minecraft1006:
      ansible_host: 10.210.30.6

minecraftv2:
  hosts:
    minecraft1001:
      ansible_host: 10.210.30.1
    minecraft1002:
      ansible_host: 10.210.30.2


minecraftpanel:
  hosts:
    minecraftpanel1001:
      ansible_host: 10.210.30.31

minecraftproxy:
  hosts:
    minecraftproxy1001:
      ansible_host: 10.210.30.101

gateway:
  hosts:
    gateway1001:
      ansible_host: 10.210.3.1

honeypot:
  hosts:
    honeypot1001:
      ansible_host: 10.210.11.100

dify:
  hosts:
    dify:
      ansible_host: 10.210.11.3

wiki:
  hosts:
    wiki1001:
      ansible_host: 10.210.11.11
